### ISSUE TITLE
Materiale di Informatica

### ISSUE THREAD

**Issue by Overlord2410** [valerionew/triennale-elettronica-polimi#10]
Ciao ragazzi, ho fatto una repository con le risoluzioni dei temi d'esame della prof Matera, per l'esame di fondamenti di informatica. Siccome mi sembra materiale utile mi piacerebbe che venisse reso disponibile a tutti tramite la vostra pagina. Siccome non sono tanto agile con Github non so come mandarvelo o come farvelo vedere ma dovrebbe essere visibile sul mio profilo. Dategli un occhiata e fatemi sapere💪🏻

**Comment by valerionew** [comment]
Ciao, grazie della segnalazione! Tutti i file nel repository sono sotto fully copyright (**All rights reserved**).   
Per poter includere il tuo contributo avrei bisogno che tu scegliessi una licenza permissiva, questo sito ti può aiutare nella scelta:
https://choosealicense.com/


Considera in ogni caso (per il futuro) che aggiungere del codice sotto completo copyright (e quindi con la dicitura *"All rights reserved"*) su GitHub non serve a molto, perché nessuno potrà toccarlo senza la tua espressa autorizzazione

**Comment by Overlord2410** [comment]
Ok, ho provveduto a inserire una licenza di copyright di tipo MIT, cercando
quella più permissiva possibile. Cosa bisogna fare ora?

Il giorno lun 21 dic 2020 alle ore 09:49 valerionew <
notifications@github.com> ha scritto:

**Comment by valerionew** [comment]
Ho aggiunto una guida https://github.com/valerionew/triennale-elettronica-polimi/blob/master/README.md
Fammi sapere se hai qualche problema o qualche domanda!

**Comment by Overlord2410** [comment]
ottimo, ho appena fatto la pull request. Fammi sapere se ho compilato in
modo corretto il file index.html

Il giorno lun 21 dic 2020 alle ore 14:11 valerionew <
notifications@github.com> ha scritto:

**Comment by valerionew** [comment]
Grazie, spostiamo la discussione su #11
