### ISSUE TITLE
Adding electronic systems notes 

### ISSUE THREAD

**Issue by valerionew** [valerionew/triennale-elettronica-polimi#25]
I have received this message:

"Ciao, sono di automazione e ho fatto il corso di electronic systems. Ho condiviso delle notes sul gruppo del corso, ma ho visto che ci sono solo 20 persone, quindi magari è più utile se caricate questo materiale anche sul vostro drive. Lo trovi sul drive di AEA ( https://aeapolimi-my.sharepoint.com/:f:/g/personal/appunti_aeapolimi_it/Er5BmlldGotJoUJFuIkIAL0BvD-fZfGUWy8NwHCcKNfzlQ ) >corsi elettivi 4-5 anno 1 sem> electronic systems> notes"

If anyone wants to help to fetch notes from the link and upload and index them correctly, any help is welcome!

**Comment by valerionew** [comment]
@FraLenzi @RhinopithecusRoxellana @TIT8 any of you want to get this?

**Comment by TIT8** [comment]
Gli appunti sono ben presi, ci sono screenshot delle slide e pezzi del libro di Zappa usati come supporto ad appunti presi a mano. Trovo utile il summary e gli esercizi, specialmente durante gli ultimi giorni di studio prima dell'esame.

Io li aggiungerei, ma bisogna capire se è possibile, gli appunti contengono parti sia del libro che delle slide ufficiali del prof (che conoscendolo non credo si opporrebbe troppo ad un utilizzo così "pulito" e ordinato del suo materiale).

@valerionew a te la responsabilità di andare in galera...

**Comment by valerionew** [comment]
Ok io posso chiedere al professore il permesso di usare questo materiale, nel caso ci dica di sì: tutti i file sono più piccoli di 100MB? Altrimenti dobbiamo comprimerli prima di caricarli
