### ISSUE TITLE
Switching to BearBlog style?

### ISSUE THREAD

**Issue by valerionew** [valerionew/triennale-elettronica-polimi#29]
Could we consider moving to Hugo with a Bear theme to improve the user experience? The appearance is very similar to the current website

Anyone brave enough to try to migrate in a branch?

 https://github.com/janraasch/hugo-bearblog

**Comment by TIT8** [comment]
I am curious, how could this theme improve the user experience?

**Comment by valerionew** [comment]
I'd say the two main things are the responsiveness of the website (to be checked), the dark/light theme and in general the appearance is more polished. 

Idk how much effort is required to migrate, and if the advantages are worth the effort

**Comment by TIT8** [comment]
Hei there, I've started the [Hugo-based version](https://github.com/TIT8/polimi-elettronica) of this project.

I only configured Hugo and the Bear theme in the _config.toml_. I decided to keep all in a new repo because in this way I can play with it without break this repo. So I've deployed a new Github Pages via Github Actions as described in the [Hugo documentation](https://gohugo.io/hosting-and-deployment/hosting-on-github/), while the templating was made as said [here](https://zwbetz.com/convert-your-plain-old-html-site-to-hugo/).

So I didn't anything special, but if someone in the while want to play with markdown file and theme of Hugo, start from [here](https://gohugo.io/getting-started/quick-start/) and play with my repo for fast prototyping.

If this will work, I will make a pull request to this repo.

**Comment by TIT8** [comment]
Now we have the Bear theme, try it [here](https://tit8.github.io/polimi-elettronica/#power-electronics)

**Comment by valerionew** [comment]
I feel like it is more polished. What do you think?

**Comment by TIT8** [comment]
Yes, I agree. The Bear theme is simple and clean. 
I found also better the experience with the download of notes (where they can be downloaded). On my browser I don't have anymore to save the file on the download folder on Windows before open it, but it is displayed immediately in the browser. I don't know if it work also in this way also for you, but I like it.

Hugo is very big, I tried themes like **docsy** by Google and **docura** and they are awesome, but our project is too simple for that style power.

**Comment by valerionew** [comment]
> On my browser I don't have anymore to save the file on the download folder on Windows before open it, but it is displayed immediately in the browser. I don't know if it work in this way also for you, but I like it.

That was actually done on purpose on the old website: the `download` keyword on the `<a>`.

I can't recall what was the exact idea behind this.

**Comment by TIT8** [comment]
Ah ok, it was intended. Indeed in the Hugo-generated html there isn't that keyword

![Screenshot (129)](https://github.com/valerionew/triennale-elettronica-polimi/assets/68781644/637a495f-645e-4133-967b-fa9bb6a8fa32)

I found that this behaviour makes the new site run smoother, but yes it's totally subjective.

**Comment by valerionew** [comment]
Do files open in the same tab on the new version?

**Comment by valerionew** [comment]
And for the last part: how do you find the process of adding new material? Is it any harder?

**Comment by TIT8** [comment]
I will write the steps in the wiki.

- This involves a shift from HTML to Markdown language. While they both belong to the Markdown family, transitioning between the two is not overly complex. You need to write in the content/_index.md file just like you did in the previous index.html.
- As for adding notes, place them in the static folder. The process remains consistent with what we currently do in this repository.

In essence, it's all about changing habits.

**Comment by TIT8** [comment]
> 

Yes

**Comment by TIT8** [comment]
> Do files open in the same tab on the new version?

Yes

**Comment by TIT8** [comment]
> And for the last part: how do you find the process of adding new material? Is it any harder?

I will write the steps in the wiki.

- This involves a shift from HTML to Markdown language. While they both belong to the Markdown family, transitioning between the two is not overly complex. You need to write in the content/_index.md file just like you did in the previous index.html.
- As for adding notes, place them in the static folder. The process remains consistent with what we currently do in this repository.

In essence, it's all about changing habits.

**Comment by TIT8** [comment]
You will find the description in the [wiki](https://github.com/TIT8/polimi-elettronica/wiki).
Please tell me if it's clear for you.

**Comment by TIT8** [comment]
I made some changes to use better the Bear theme. Now I'm reaching a stable version of the new [site](https://tit8.github.io/polimi-elettronica/).

I like it, but maybe I am biased.

**Comment by TIT8** [comment]
> I'd say the two main things are the responsiveness of the website (to be checked), the dark/light theme and in general the appearance is more polished. 
> 
> Idk how much effort is required to migrate, and if the advantages are worth the effort 


From my perspective, your intuitions were correct.

**Comment by valerionew** [comment]
Finalmente ho avuto tempo di guardarci. Devo dire che è molto figo.  Cosa manca per il merge?

Per il futuro sarebbe ancora più figo se riuscissimo a creare un upload guidato, tipo un form in cui caricare file e descrizioni e che dall'invio del form crea automaticamente la PR. Anche se non credo che si possa fare senza backend, e forse è un po' complicato per questo sito

**Comment by TIT8** [comment]
Molto bene! 
Giusto una conferma, ti funziona tutto giusto? Hai provato a toccare i link, switchare tra dark e light theme, inviare un messaggio via form? Mi darebbe una mano un occhio esterno nel debug.

Allora posso provare subito a fare una pull request. Alcuni accorgimenti li devo fare.

1. Dovrei aver fatto il sito abbastanza generale da non avere problemi con il cambio di url per le Github Pages, dovremo solo passare ad un deploy non via branch ma via github actions come descritto sul [sito di Hugo](https://gohugo.io/hosting-and-deployment/hosting-on-github/) (basta cambiare un' impostazione e il sistema fa tutto in automatico).

2. Se vogliamo testarlo estensivamente prima di fare il merge tra nuovo branch e master, possiamo usare Netlify che a differenza delle Github Pages è in grado di fare il deploy di branch che non siano il master. Questo commento è molto probabilmente inutile, ma mi sono innamorato di Netlify (è velocissimo a fare il deploy, Github actions ci mette 15 minuti, Netlify 1, e non ha problemi con il size della repo, Github actions ti dice che per repo con size sopra 1GB potrebbe fallire il deploy; mai fallito per ora se non per colpa mia).

3. Dovrò solo sistemare alcuni link che portano alla mia repo, ma una volta che il sito è funzionante si tratta di fare una pull request con i cambiamenti. 

4. Poi copierei così com'è la wiki per le istruzioni su come contribuire, ma se non ti piace l'idea si può benissimo portare il contenuto nel README. Non so il perché, mi piacciono un sacco le wiki di Github per le documentazioni.

5.  Gran bella idea quella del form guidato, posso provarla sulla [API](https://github.com/TIT8/go-api) che ho scritto per il form del nuovo sito. Se tu hai voglia di provare e conosci Go, cioè hai letto cinque minuti fa la [go-by-example](https://gobyexample.com/), ti faccio collaboratore anche lì e lo vediamo in un nuovo branch. Credo che Go lato backend abbia qualche soluzione per lavorare con Git.

6. Aggiungo già le ultime pull request dei ragazzi su questa repo.

**Comment by TIT8** [comment]
Ok, dai allora inizio a fare il grande cambiamento.

Io mi occupo delle Github Pages e della wiki, @valerionew devi occuparti di Netlify, perché solo l'admin può fare il deploy di una repo (creare un account Netlify è gratuito, l'uso anche, entro limiti che non dovremmo raggiungere). 
Le istruzioni sono [qui](https://gohugo.io/hosting-and-deployment/hosting-on-netlify/), anche se durante il processo il sito di Netlify è molto più chiaro della documentazione di Hugo. Consigli miei:
- il branch di cui fare il deploy lo puoi scegliere una volta linkata la repo, la gui ti aiuterà
- l'unica enviroment variable utile è `HUGO_VERSION=0.117.0`, il sito nella gui ti da la possibilità di inserirla senza creare file `netlify.toml` strani
- il comando per la build sarà `hugo --gc --minify`
- gli altri parametri sono inutili e puoi lasciarli predefiniti
- puoi cambiare il nome del sito nello url andando nelle impostazioni del domain

Siccome dovrai scegliere quale branch fare il deploy ci sono due opzioni:
- facciamo subito il **merge** dei branch **hugo** e **master** (nel caso di problemi, il `revert` ci salverà) e fai il deploy del master e io quello sulle Github Pages (che funzionano solo sui master branch)
- teniamo ancora il branch separato, fai il deploy di **hugo**, testiamo il tutto e poi faremo il merge (in questo caso le Github Pages non possono farci vedere il nuovo sito)

Qui dipende dal nostro coraggio, io mi sono già stufato di testare, ma l'admin sei te quindi la patata bollente la prendi tu: ho il via libera a tentare il primo merge o è meglio essere cauti?

**Comment by valerionew** [comment]
> teniamo ancora il branch separato, fai il deploy di hugo, testiamo il tutto e poi faremo il merge (in questo caso le Github Pages non possono farci vedere il nuovo sito)


This please. Siamo pur sempre in sessione :)

**Comment by TIT8** [comment]
Va bene 😂 . Ho sistemato la wiki. 
Gioca con Netlify e il branch hugo, quando hai finito metti il link nel readme. Vorrai mica giocarci da solo, io sono geloso?

**Comment by valerionew** [comment]
Building

**Comment by valerionew** [comment]
Live at https://triennale-elettronica-polimi.netlify.app/

**Comment by TIT8** [comment]
> Live at https://triennale-elettronica-polimi.netlify.app/

Sei stato una furia 🔝

**Comment by valerionew** [comment]
Come si collega la build di netlify a github.io però?

**Comment by TIT8** [comment]
github.io è un'altra cosa, sono due deploy (e host) separati. Il deploy sulle github pages è fatto via uno script `(hugo.yaml)` che trovi nella cartella [.github/workflows](https://github.com/valerionew/triennale-elettronica-polimi/tree/hugo/.github/workflows).

Il [sito di Hugo](https://gohugo.io/hosting-and-deployment/hosting-on-github/) mi ha detto come fare.

**Comment by valerionew** [comment]
Ok perfetto!

**Comment by TIT8** [comment]
Proporrei ora di fare la pull request per preparare il merge, Netlify ci manderà in automatico una preview (che sarà lo stesso sito che vediamo ora, ma solo con un dominio differente). Poi sarai tu a schiacciare il fatidico bottone 🥇 .

Un appunto che mi ero dimenticato di dirti: durante lo sviluppo avevo tolto il tuo **google tag manager** per non crearti dei falsi positivi nelle analisi. Se lo usi ancora, te lo rimetto (non si fa da qua, devo inserirlo nel mio [fork](https://github.com/TIT8/hugo-bearblog) del tema BearBlog). Dimmi te.

**Comment by valerionew** [comment]
Procediamo!

**Comment by valerionew** [comment]
Si, direi di tenere analytics. Penso di poterti anche dare accesso se hai un account Google

**Comment by TIT8** [comment]
Ok, 5 minuti, copio-incollo-arrivo.

**Comment by TIT8** [comment]
> Si, direi di tenere analytics. Penso di poterti anche dare accesso se hai un account Google

No, grazie, non voglio altre mail da Google, sono già pieno di spam.

**Comment by TIT8** [comment]
Ok, pull request fatta, perdonami se ci ho messo molto più di 5 minuti, ma la pull request è troppo grande per il sito di Github, ho dovuto imparare ad usare la [CLI](https://cli.github.com/) di Github per farlo. Ora è a posto.

**Comment by valerionew** [comment]
Closed by #34

Thank you very much @TIT8 for your effort, the result looks amazing!

**Comment by TIT8** [comment]
@valerionew per le github pages devi solo cambiare una cosa che può fare solo l'owner, come scritto sul sito di [Hugo](https://gohugo.io/hosting-and-deployment/hosting-on-github/)

**Comment by TIT8** [comment]
> @valerionew per le github pages devi solo cambiare una cosa che può fare solo l'owner, come scritto sul sito di [Hugo](https://gohugo.io/hosting-and-deployment/hosting-on-github/).
> 
> Sostanzialmente devi dire che invece che fare il deploy da branch, lo vuoi da Github Action (è ancora in beta, ma oramai quasi stabile come soluzione)

This

**Comment by valerionew** [comment]
Giuro che l'ho fatto

![image](https://github.com/valerionew/triennale-elettronica-polimi/assets/17505995/a70cd3c4-d68c-4718-b3bc-c524873f23dd)

**Comment by TIT8** [comment]
Ok allora aspettiamo i soliti 20 minuti (dove gli artifacts ce ne mettono 12)

**Comment by valerionew** [comment]
Questa run dovrebbe essere quella buona

https://github.com/valerionew/triennale-elettronica-polimi/actions/runs/6195961295/job/16821679163

**Comment by TIT8** [comment]
La vedo, se inizia il deploy vuol dire che è tutto a posto (potrebbe fallire per via del size della repo, motivo per cui mi sono buttato su Netlify)

**Comment by valerionew** [comment]
Nel caso peggiore credo che potremmo fare la build di una pagina che restituisce 301 redirect alla build di netlify, immagino

**Comment by valerionew** [comment]
deployed
