### ISSUE TITLE
Weird webiste?

### ISSUE THREAD

**Issue by valerionew** [valerionew/triennale-elettronica-polimi#39]
https://github.com/valerionew/triennale-elettronica-polimi/blob/0a9465b6bc0f2db6be4c4f90e5f8b8edfeb3b582/content/_index.md?plain=1#L323

I'm not sure which webiste we are linking here. Is it safe? 

@TIT8 can you help me clarify where this came from?

**Comment by valerionew** [comment]
It comes from #35 but I'm not able to track it further

**Comment by TIT8** [comment]
The website is [Studwiz](https://www.studwiz.com/). The link leads to notes on Biochip that I and others have found useful in the past. The link was shared within the Biochip group on Telegram. You can't share the PDF directly, but you can access and view the notes from Studwiz.

***If you don't want these links, we can remove them.***

I added it as #35  when I was including notes for a student. I decided to add only the PDFs on Telegram that were useful and well done and hadn't been added before. When I came across that link, I remembered its function and decided to include it.

**Comment by valerionew** [comment]
Ok so now I understand that it was the old andreadd.it.

I don't love the spirit of the webiste, it is not as *free as in freedom* as this one, but whatever. If it is helpful I'm okay with the link staying
