### ISSUE TITLE
Formulario Elettrotecnica

### ISSUE THREAD

**Issue by PietroG51** [valerionew/triennale-elettronica-polimi#4]
Allego formulario di elettrotecnica
https://drive.google.com/file/d/1AxkdTzonc9JqrrF4X8wQbMBMrXheT9u2/view?usp=sharing

**Comment by valerionew** [comment]
@PietroG51 grazie!
Possiamo considerarlo disponibile con la licenza "standard" della raccolta? 
https://creativecommons.org/licenses/by-nc-sa/4.0/deed.it

**Comment by PietroG51** [comment]
sisi

**Comment by valerionew** [comment]
Perfetto, procedo al merge!
