### ISSUE TITLE
Compression of PDF

### ISSUE THREAD

**Issue by TIT8** [valerionew/triennale-elettronica-polimi#58]
For reference, see #57.

Is it possible to use Github Action to do the compression every time we push a pdf in a specific directory?

I know the issue with OCR, but, for new notes at least, Github Action could return us also a compressed version of what is pushed by student and then, during the review, we can decide if keep it o discard it.

The question can be stupid because I don't know how the compression is done, so sorry in advance.

**Comment by valerionew** [comment]
It is not impossible, but does it make any sense to have a github action commit to the repo?

**Comment by TIT8** [comment]
Ehehe, I don’t know.

**Comment by valerionew** [comment]
Overview of all files with no text in them:

```
static/TAB1/QuantumCommunications/QuantumCommuncations-AlMuktash.pdf: 18.05 MB
static/TAB1/AutomationVehicles/compressed-AutomationandControlinVehicles-MattiaAmadori.pdf: 17.97 MB
static/TAB1/AutomationVehicles/compressed-Suspension-MattiaAmadori.pdf: 3.78 MB
static/5/MixedSignal/compressed-MixedSignals-MattiaAmadori.pdf: 36.59 MB
static/5/EDFBI/compressed-EDFBI-MattiaAmadori.pdf: 43.68 MB
static/5/MicroelectronicTechnologies/compressed-MicrotechNotes-MikelKumria.pdf: 55.80 MB
static/1/GAL/carraraEstratto.pdf: 5.08 MB
static/3/ESS/elettronica_stato_solidoAlMuktash.pdf: 20.96 MB
static/3/Optoelettronica/optoelettronicaAlMuktash.pdf: 13.30 MB
static/3/Analogica/02_TransistoreBipolare.pdf: 0.27 MB
static/3/Analogica/01_diodo.pdf: 0.43 MB
static/3/Trasformate/analisi_funzAlMuktash.pdf: 17.62 MB
static/4/Analog/compressed-AnalogDesign-MattiaAmadori.pdf: 21.03 MB
static/4/Analog/ACD_Summaries_Sera.pdf: 85.23 MB
static/4/Analog/compressed-AnalogRiassunto-MattiaAmadori.pdf: 2.43 MB
static/4/SignalRecovery/compressed-SignalRecovery-MattiaAmadori.pdf: 39.08 MB
static/4/ElectronicSystems/compressed-ElectronicSystems-MattiaAmadori.pdf: 13.59 MB
static/4/ElectronicSystems/SlidesAmadori/compressed-T01-basics-MattiaAmadori.pdf: 4.04 MB
static/4/Biochip/compressed-Biochip-MattiaAmadori.pdf: 15.87 MB
static/4/Biochip/compressed-BiochipWithNotes-MattiaAmadori.pdf: 16.29 MB
static/4/RFCircuitDesign/compressed-RFCircuitDesign-MattiaAmadori.pdf: 50.59 MB
static/4/MEMS/compressed-MEMS-MattiaAmadori.pdf: 40.06 MB
static/2/ArchCalc/appuntiArchCalc.pdf: 12.33 MB
static/2/FDA/appuntiTombolan/61_TOMBOLAN_AUTOMATICA_CORNO_2018.pdf: 23.05 MB
static/2/FDA/appuntiTombolan/33_TOMBOLAN_AUTOMATICA_CORNO_2018.pdf: 24.80 MB
static/2/FDA/appuntiTombolan/1_TOMBOLAN_AUTOMATICA_CORNO_2018.pdf: 24.55 MB
static/2/FDE/appuntiTombolan/22_TOMBOLAN_FDE_2018_APPUNTI.pdf: 24.53 MB
static/2/FDE/appuntiTombolan/53_TOMBOLAN_FDE_2018_APPUNTI.pdf: 23.10 MB
static/2/FDE/appuntiTombolan/73_TOMBOLAN_FDE_2018_APPUNTI.pdf: 4.29 MB
static/2/FDE/appuntiTombolan/38_TOMBOLAN_FDE_2018_APPUNTI.pdf: 22.84 MB

Total size: 681.23 MB
```

Out of 2.7 GB of files

**Comment by TIT8** [comment]
How can I use this tool?
Is there a documentation of the scripts you push on the repo?

Maybe we can describe the usage in the wiki.

**Comment by TIT8** [comment]
> Overview of all files with no text in them:
> 
> ```
> static/TAB1/QuantumCommunications/QuantumCommuncations-AlMuktash.pdf: 18.05 MB
> static/TAB1/AutomationVehicles/compressed-AutomationandControlinVehicles-MattiaAmadori.pdf: 17.97 MB
> static/TAB1/AutomationVehicles/compressed-Suspension-MattiaAmadori.pdf: 3.78 MB
> static/5/MixedSignal/compressed-MixedSignals-MattiaAmadori.pdf: 36.59 MB
> static/5/EDFBI/compressed-EDFBI-MattiaAmadori.pdf: 43.68 MB
> static/5/MicroelectronicTechnologies/compressed-MicrotechNotes-MikelKumria.pdf: 55.80 MB
> static/1/GAL/carraraEstratto.pdf: 5.08 MB
> static/3/ESS/elettronica_stato_solidoAlMuktash.pdf: 20.96 MB
> static/3/Optoelettronica/optoelettronicaAlMuktash.pdf: 13.30 MB
> static/3/Analogica/02_TransistoreBipolare.pdf: 0.27 MB
> static/3/Analogica/01_diodo.pdf: 0.43 MB
> static/3/Trasformate/analisi_funzAlMuktash.pdf: 17.62 MB
> static/4/Analog/compressed-AnalogDesign-MattiaAmadori.pdf: 21.03 MB
> static/4/Analog/ACD_Summaries_Sera.pdf: 85.23 MB
> static/4/Analog/compressed-AnalogRiassunto-MattiaAmadori.pdf: 2.43 MB
> static/4/SignalRecovery/compressed-SignalRecovery-MattiaAmadori.pdf: 39.08 MB
> static/4/ElectronicSystems/compressed-ElectronicSystems-MattiaAmadori.pdf: 13.59 MB
> static/4/ElectronicSystems/SlidesAmadori/compressed-T01-basics-MattiaAmadori.pdf: 4.04 MB
> static/4/Biochip/compressed-Biochip-MattiaAmadori.pdf: 15.87 MB
> static/4/Biochip/compressed-BiochipWithNotes-MattiaAmadori.pdf: 16.29 MB
> static/4/RFCircuitDesign/compressed-RFCircuitDesign-MattiaAmadori.pdf: 50.59 MB
> static/4/MEMS/compressed-MEMS-MattiaAmadori.pdf: 40.06 MB
> static/2/ArchCalc/appuntiArchCalc.pdf: 12.33 MB
> static/2/FDA/appuntiTombolan/61_TOMBOLAN_AUTOMATICA_CORNO_2018.pdf: 23.05 MB
> static/2/FDA/appuntiTombolan/33_TOMBOLAN_AUTOMATICA_CORNO_2018.pdf: 24.80 MB
> static/2/FDA/appuntiTombolan/1_TOMBOLAN_AUTOMATICA_CORNO_2018.pdf: 24.55 MB
> static/2/FDE/appuntiTombolan/22_TOMBOLAN_FDE_2018_APPUNTI.pdf: 24.53 MB
> static/2/FDE/appuntiTombolan/53_TOMBOLAN_FDE_2018_APPUNTI.pdf: 23.10 MB
> static/2/FDE/appuntiTombolan/73_TOMBOLAN_FDE_2018_APPUNTI.pdf: 4.29 MB
> static/2/FDE/appuntiTombolan/38_TOMBOLAN_FDE_2018_APPUNTI.pdf: 22.84 MB
> 
> Total size: 681.23 MB
> ```
> 
> Out of 2.7 GB of files

Still incredible numbers.
