### ISSUE TITLE
appunti chimica

### ISSUE THREAD

**Issue by PietroG51** [valerionew/triennale-elettronica-polimi#6]
https://drive.google.com/file/d/1lSFHCdXmxi_AD_2wK58zesxOWha2FBLR/view?usp=sharing

**Comment by valerionew** [comment]
Aggiunto in https://github.com/valerionew/triennale-elettronica-polimi/commit/17374871796ff7f656f238141aa2e59047a22e0f, grazie!
Ho immaginato che andasse bene la stessa licenza che mi hai confermato in #4 
Se ti va, la metteresti anche in copertina per i prossimi file?
