### ISSUE TITLE
Appunti architetture

### ISSUE THREAD

**Issue by PietroG51** [valerionew/triennale-elettronica-polimi#8]
[ArchitettureDeiCalcolatori - Pietro Giannoccaro.pdf](https://github.com/valerionew/triennale-elettronica-polimi/files/5128844/ArchitettureDeiCalcolatori.-.Pietro.Giannoccaro.pdf)

scusa se non metto mai la licenza ma non ho ben capito come e dove metterla. Comunque la licenza va bene sempre la stessa

**Comment by valerionew** [comment]
Grazie!
Aggiunti in 6acd694
